version: '3.8'
services:
  backend:
    # env_file:
    #   - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - 8000

  frontend:
    # env_file:
    #   - frontend/.env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3006:3006"
    expose:
      - 3006